# Generated by Django 4.2.4 on 2023-08-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_delete_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('password', models.IntegerField()),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
    ]
