# Generated by Django 4.2.4 on 2023-08-27 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='estudiante',
        ),
    ]
