# Generated by Django 4.2.5 on 2023-09-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_estudiante_options_alter_estudiante_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(unique=True)),
                ('password', models.CharField()),
                ('grupo', models.CharField(max_length=50)),
            ],
        ),
    ]
